title: Trac Quang Thinh
url: "https://tracthinh.github.io"
# baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: # 
google_analytics: G-0K1QMSJSPX

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Tools"
   link: "tool"

